### ISSUE TITLE
Convites banca Evillyn

### ISSUE THREAD

**Issue by p3palazzo** [dmcpatrimonio/estrategias-adaptativas#19]
@p3palazzo : fazer convites
@Evillynb : previsão de datas 20/06–10/07

- [x] Interno: Rossetti
- [x] Externo: Hugo Segawa
- [x] Suplente: Sylvia

**Comment by Evillynb** [comment]
Acho que podemos fazer a qualificação entre os dias 20/06 e 10/07, a depender da disponibilidade da banca.
